package org.chrisle.netbeans.plugins.nbyeoman.wizard.rungenerator;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ChrisLE
 */
public class YeomanRunGeneratorPanelVisual extends JPanel implements DocumentListener {

    /**
     * Creates new form YeomanRunGeneratorPanelVisual
     */
    public YeomanRunGeneratorPanelVisual(YeomanRunGeneratorWizardPanel wizardPanel) {
        initComponents();
        
        String cmd = System.getProperty("user.home") + "\\AppData\\Roaming\\npm\\yo.cmd angular";
        
        try {
            Process process = Runtime.getRuntime().exec(cmd, null, null);
            
            readProcessOutput(process);
        } catch( IOException e ) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yoOutput = new javax.swing.JTextArea();

        yoOutput.setColumns(20);
        yoOutput.setRows(5);
        jScrollPane1.setViewportView(yoOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea yoOutput;
    // End of variables declaration//GEN-END:variables

    private static void readProcessOutput(final Process process) {
        read(process.getInputStream(), yoOutput);
//        read(process.getErrorStream(), System.err);
    }

    private static void read(InputStream inputStream, JTextArea output) {
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
            
            JOptionPane.showMessageDialog(null, reader.readLine());

            String line;
            while( (line = reader.readLine()) != null ) {
//                out.println(line);
                JOptionPane.showMessageDialog(null, line);
//                output.setText(line);
            }

        } catch( IOException e ) {
            e.printStackTrace();
        } finally {

            try {
                inputStream.close();
            } catch( IOException e ) {
                e.printStackTrace();
            }
        }
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}